### ISSUE TITLE
Minor styling issues

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-image-zones#6]
Two minor styling issues:
1. There is a border around the SVG only when it gets the focus. I would like to have the border to be available always.
2. It seems that the SVG is a bit too large to fit on my screen.

![image](https://user-images.githubusercontent.com/14224149/141695551-ed6dac93-26e7-4143-8252-95efea2b756e.png)

**Comment by hotNipi** [comment]
Pushed and update. You can now adjust the size of the content with the sizes of the svg element.
` <svg id="svg_drawing" tabindex="0" width="400" height="300" ....`

**Comment by bartbutenaers** [comment]
Thanks @hotNipi!!!!
